### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Deviltriss** [fmmmlee/D2Solo#2]
I love your program and it works great, just a question.
Albeit it could be a stupid question, however is there any way to have solo enabled but still be able to be 2 people in a fireteam?

Me and my friend would love to play together in strikes alone, without that third person.
Is there any way of doing this with this program/or another way?
One of us always gets thrown out, if enabled.

many regards.

**Comment by fmmmlee** [comment]
Unfortunately, the way it works is basically blocking all communication with other player computers over the network, and this includes fireteams; as far as I know, it's not possible to allow fireteams to stick together but still block matchmaking. If someone is able to determine a way though, I'd be glad to implement it!
